version: "3"
tasks:
  # Запуск всех сервисов через Docker Compose
  up:
    desc: Start service
    cmds:
      - docker-compose up -d --build
    env:
      BOT_TOKEN: "<token>"

  # Остановка всех сервисов
  down:
    desc: Stop all services
    cmds:
      - docker-compose down
